### ISSUE TITLE
显示 Egret Fast Debug: ****.ts编译完成   js并未生成改变

### ISSUE THREAD

**Issue by Wangpengli0419** [huyaoduo/EgretFastDebug#7]
显示 Egret Fast Debug: ****.ts编译完成   js并未生成改变
请问下我怎么可以自己开启调试模式 看看哪里有问题呀

**Comment by Wangpengli0419** [comment]
vscode和wing都不可以

**Comment by huyaoduo** [comment]
> vscode和wing都不可以

安装node.js了吗
